/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/castle.glb 
Author: nigelgoh (https://sketchfab.com/nigelgoh)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/castle-on-hills-b874cb19b42741729b950f6afbdf0dea
Title: Castle On Hills
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import { MeshStandardMaterial } from 'three'
export function Castle(props) {
  // "#131392"
  const { nodes, materials } = useGLTF('models/castle.glb');
  const land = new MeshStandardMaterial({ color: "#012701"})
  materials.buildings= new MeshStandardMaterial({ color: "#3b3838"})
  materials.roof= new MeshStandardMaterial({ color: "#0a3a75"});
  materials.water=new MeshStandardMaterial({ color: "#0a3a75"});
  materials.plants=new MeshStandardMaterial({ color: "#193e19"});
    materials.plant2=new MeshStandardMaterial({ color: "#023b02"});
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <mesh geometry={nodes.polySurface299_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface299_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube170_rocks1_0.geometry} material={materials.rocks1} />
            <mesh geometry={nodes.polySurface341_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface341_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface303_grass_0.geometry} material={land} />
            <mesh geometry={nodes.polySurface304_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface265_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface266_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface267_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface268_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface269_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube104_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube105_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube105_water_0.geometry} material={materials.water} />
            <mesh geometry={nodes.pCube106_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface271_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface272_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube107_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube110_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube111_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface289_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface290_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface291_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface292_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface264_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface264_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface298_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface298_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface262_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface262_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface270_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface293_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface294_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface295_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface296_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface297_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface307_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface308_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface309_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface309_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube119_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube119_water_0.geometry} material={materials.water} />
            <mesh geometry={nodes.pCube120_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube121_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube122_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube123_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube124_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube125_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube126_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube128_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube129_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube130_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube131_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube132_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube133_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube134_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube135_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface305_roof_0.geometry} material={materials.roof} />
            <mesh geometry={nodes.polySurface305_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube139_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube140_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube141_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube142_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube143_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube144_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube145_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube147_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube148_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube149_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube150_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube151_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface311_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface312_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube152_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube153_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube154_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube155_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube156_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube157_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube158_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube159_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube160_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube161_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube162_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube163_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube166_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube167_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube168_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube169_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface313_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface314_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface319_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface320_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface321_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface322_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface323_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface324_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface325_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface334_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface335_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface346_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface347_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface348_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface349_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface350_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface351_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface352_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface353_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube185_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube185_water_0.geometry} material={materials.water} />
            <mesh geometry={nodes.pCylinder1_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCube187_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube188_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube189_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube190_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCylinder2_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder3_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder4_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder5_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.polySurface336_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface337_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface338_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface339_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface340_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCylinder6_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder8_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder9_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder10_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder13_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder14_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder15_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder16_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder17_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder18_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder19_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder20_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder21_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder22_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder23_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder24_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pPlane127_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.pCylinder25_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder26_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder27_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCube191_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube192_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube193_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube194_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube195_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube196_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube197_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube198_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube201_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube202_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface342_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pPlane128_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.pPlane129_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.pPlane130_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.group6_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCylinder28_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder29_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder30_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder31_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder32_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder33_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder34_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder35_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.polySurface333_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube203_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube204_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube205_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube206_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube207_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube208_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube209_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube210_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube211_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCylinder36_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCube212_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube213_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube214_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pPlane132_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.polySurface343_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface343_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.polySurface344_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface344_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.polySurface345_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.polySurface345_flag_0.geometry} material={materials.flag} />
            <mesh geometry={nodes.pCylinder41_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder42_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCube215_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube216_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube217_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube218_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube219_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube220_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube221_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube222_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCube223_buildings_0.geometry} material={materials.buildings} />
            <mesh geometry={nodes.pCylinder43_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder44_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder45_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder46_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder47_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder48_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder49_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder50_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder51_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder52_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder53_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder54_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder55_plant2_0.geometry} material={materials.plant2} />
            <mesh geometry={nodes.pCylinder56_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder57_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder58_plants_0.geometry} material={materials.plants} />
            <mesh geometry={nodes.pCylinder59_plants_0.geometry} material={materials.plants} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/castle.glb')
