/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/free_fire.glb 
Author: ROCK FF 99 (https://sketchfab.com/amansoyal781)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-fire-lone-wolf-mode-3d-model-e44f52081bee470faae87465c29833bd
Title: Free fire lone wolf mode 3d model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/free_fire.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Cargo_container_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Container_Red_D} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Factory_Building001} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Factory_Wood} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Factory_Wood} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Factory_Wood} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Factory_Building002} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Factory_Wood.002']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Factory_Wood.015']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/free_fire.glb')
